name: mapa_osm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icone.png
    - assets/iconePino.png
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icone.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icone.png

  android: true
  ios: true

  android_gravity: center
  ios_content_mode: center
